// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("yarnbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJys10Fy2zoMANB9TsELRAfw7v8DdNFdVx6KhGQ2JMECoFP39B1ZcTSxY1cKsVM0wxcKBGjg2bzAaWdOlnIPVp6MkSARdubHf9+/mf/nVx7YUSgSMO+ejBkCRM/TkzHPJtsEOyOnAucX5vy4m9hXJP/27kpY1k3/uLOldMGvXG4+Xz/92SaIHblRWB+EO0JloDaBxUrjJn5VqI1EoYAU5PRBiZjHLQSOBMwNhJB1LyGP+0rxAyPwW9YzDrPYkIH2Ea9SZBvEYkk+rPfLYa1YP4Qc+NAAQLSFwXepJapDyDbupzyrjfViY0RnBfwS4paNLdzRIYEOlfo1zOfKeRt7BtewkwQJ6dSIFAJIRS3QC9cSnUVpOi4XKwvQRHLnMJUIAl4DG2yIOtJLiEpSgezD+8omimrOShTXPgVZGfb71pKcSwGqiRsit8ojYKBj6wbn8la4b67Bow3R9hG0wMvnanmCYmMzltEDd9ZJOIKG5MFhSoE5YG492luxOf1mMiKLhkPQIzaX2GzxoYrH16xhnVNDA6r5ADbKYVUbeh+bf560rqSLdilQFU3nMnrDvhb/ZAuBrw66n9ivH+ceGBtGugfKlmnmAbNlrnrAbBjwHm+GZC/hKj53hoEH0DxRaEhzC6Ah1R4o/LnK5R4xgs3bpGQLd1ZkajO3tHOryfV93WqSq3PAPNTWCpzZ43h7JF+0NvXW/8I07pgENILaN86P2vlyo6qkzI2qljXvsm5QtXLn4mmkDx/qMES9b3VYs1wP1iNhLRfnlG0KbmeE6qd34t8AAAD//3OUqnw="
}
